<?php
/*
* ! The icons lists are reused in multiple locations; make sure to update all when needed !
* ! Remember to sync with the arrays in options.php and in the styling file !
*/

/*** landing page blocks icons ***/
$block_icons = array(
	'no-icon' => '&nbsp;',
	'toggle' => 'e003',
	'layout' => 'e004',
	'lock' => 'e007',
	'unlock' => 'e008',
	'target' => 'e012',
	'disc' => 'e019',
	'microphone' => 'e048',
	'play' => 'e052',
	'cloud2' => 'e065',
	'cloud-upload' => 'e066',
	'cloud-download' => 'e067',
	'plus2' => 'e114',
	'minus2' => 'e115',
	'check2' => 'e116',
	'cross2' => 'e117',
	'users2' => 'e00a',
	'user' => 'e00b',
	'trophy' => 'e00c',
	'speedometer' => 'e00d',
	'screen-tablet' => 'e00f',
	'screen-smartphone' => 'e01a',
	'screen-desktop' => 'e01b',
	'plane' => 'e01c',
	'notebook' => 'e01d',
	'magic-wand' => 'e01e',
	'hourglass2' => 'e01f',
	'graduation' => 'e02a',
	'fire' => 'e02b',
	'eyeglass' => 'e02c',
	'energy' => 'e02d',
	'chemistry' => 'e02e',
	'bell' => 'e02f',
	'badge' => 'e03a',
	'speech' => 'e03b',
	'puzzle' => 'e03c',
	'printer' => 'e03d',
	'present' => 'e03e',
	'pin' => 'e03f',
	'picture2' => 'e04a',
	'map' => 'e04b',
	'layers' => 'e04c',
	'globe' => 'e04d',
	'globe2' => 'e04e',
	'folder' => 'e04f',
	'feed' => 'e05a',
	'drop' => 'e05b',
	'drawar' => 'e05c',
	'docs' => 'e05d',
	'directions' => 'e05e',
	'direction' => 'e05f',
	'cup2' => 'e06b',
	'compass' => 'e06c',
	'calculator' => 'e06d',
	'bubbles' => 'e06e',
	'briefcase' => 'e06f',
	'book-open' => 'e07a',
	'basket' => 'e07b',
	'bag' => 'e07c',
	'wrench' => 'e07f',
	'umbrella' => 'e08a',
	'tag' => 'e08c',
	'support' => 'e08d',
	'share' => 'e08e',
	'share2' => 'e08f',
	'rocket' => 'e09a',
	'question' => 'e09b',
	'pie-chart2' => 'e09c',
	'pencil2' => 'e09d',
	'note' => 'e09e',
	'music-tone-alt' => 'e09f',
	'list2' => 'e0a0',
	'like' => 'e0a1',
	'home2' => 'e0a2',
	'grid' => 'e0a3',
	'graph' => 'e0a4',
	'equalizer' => 'e0a5',
	'dislike' => 'e0a6',
	'calender' => 'e0a7',
	'bulb' => 'e0a8',
	'chart' => 'e0a9',
	'clock' => 'e0af',
	'envolope' => 'e0b1',
	'flag' => 'e0b3',
	'folder2' => 'e0b4',
	'heart2' => 'e0b5',
	'info' => 'e0b6',
	'link' => 'e0b7',
	'refresh' => 'e0bc',
	'reload' => 'e0bd',
	'settings' => 'e0be',
	'arrow-down' => 'e604',
	'arrow-left' => 'e605',
	'arrow-right' => 'e606',
	'arrow-up' => 'e607',
	'paypal' => 'e608',
	'home' => 'e800',
	'apartment' => 'e801',
	'data' => 'e80e',
	'cog' => 'e810',
	'star' => 'e814',
	'star-half' => 'e815',
	'star-empty' => 'e816',
	'paperclip' => 'e819',
	'eye2' => 'e81b',
	'license' => 'e822',
	'picture' => 'e827',
	'book' => 'e828',
	'bookmark' => 'e829',
	'users' => 'e82b',
	'store' => 'e82d',
	'calendar' => 'e836',
	'keyboard' => 'e837',
	'spell-check' => 'e838',
	'screen' => 'e839',
	'smartphone' => 'e83a',
	'tablet' => 'e83b',
	'laptop' => 'e83c',
	'laptop-phone' => 'e83d',
	'construction' => 'e841',
	'pie-chart' => 'e842',
	'gift' => 'e844',
	'diamond' => 'e845',
	'cup3' => 'e848',
	'leaf' => 'e849',
	'earth' => 'e853',
	'bullhorn' => 'e859',
	'hourglass' => 'e85f',
	'undo' => 'e860',
	'redo' => 'e861',
	'sync' => 'e862',
	'history' => 'e863',
	'download' => 'e865',
	'upload' => 'e866',
	'bug' => 'e869',
	'code' => 'e86a',
	'link2' => 'e86b',
	'unlink' => 'e86c',
	'thumbs-up' => 'e86d',
	'thumbs-down' => 'e86e',
	'magnifier' => 'e86f',
	'cross3' => 'e870',
	'menu' => 'e871',
	'list' => 'e872',
	'warning' => 'e87c',
	'question-circle' => 'e87d',
	'check' => 'e87f',
	'cross' => 'e880',
	'plus' => 'e881',
	'minus' => 'e882',
	'layers2' => 'e88e',
	'text-format' => 'e890',
	'text-size' => 'e892',
	'hand' => 'e8a5',
	'pointer-up' => 'e8a6',
	'pointer-right' => 'e8a7',
	'pointer-down' => 'e8a8',
	'pointer-left' => 'e8a9',
	'heart' => 'e930',
	'cloud' => 'e931',
	'trash' => 'e933',
	'user2' => 'e934',
	'key' => 'e935',
	'search' => 'e936',
	'settings2' => 'e937',
	'camera' => 'e938',
	'tag2' => 'e939',
	'bulb2' => 'e93a',
	'pencil' => 'e93b',
	'diamond2' => 'e93c',
	'location' => 'e93e',
	'eye' => 'e93f',
	'bubble' => 'e940',
	'stack' => 'e941',
	'cup' => 'e942',
	'phone' => 'e943',
	'news' => 'e944',
	'mail' => 'e945',
	'news2' => 'e948',
	'paperplane' => 'e949',
	'params2' => 'e94a',
	'data2' => 'e94b',
	'megaphone' => 'e94c',
	'study' => 'e94d',
	'chemistry2' => 'e94e',
	'fire2' => 'e94f',
	'paperclip2' => 'e950',
	'calendar2' => 'e951',
	'wallet' => 'e952',
);

$meta_icons = array(
	'user-female' => "\e000",
	'screen-smartphone' => "\e010",
	'screen-desktop' => "\e011",
	'plane' => "\e012",
	'notebook' => "\e013",
	'moustache' => "\e014",
	'energy' => "\e020",
	'emoticon-smile' => "\e021",
	'disc' => "\e022",
	'credit-card' => "\e025",
	'chemistry' => "\e026",
	'user' => "\e005",
	'speedometer' => "\e007",
	'screen-tablet' => "\e00f",
	'magic-wand' => "\e017",
	'hourglass' => "\e018",
	'game-controller' => "\e01b",
	'fire' => "\e01c",
	'eyeglasses' => "\e01d",
	'envelope-open' => "\e01e",
	'bell' => "\e027",
	'badge' => "\e028",
	'wallet' => "\e02a",
	'vector' => "\e02b",
	'speech' => "\e02c",
	'puzzle' => "\e02d",
	'pin' => "\e031",
	'picture' => "\e032",
	'map' => "\e033",
	'layers' => "\e034",
	'handbag' => "\e035",
	'globe-alt' => "\e036",
	'globe' => "\e037",
	'frame' => "\e038",
	'folder-alt' => "\e039",
	'film' => "\e03a",
	'feed' => "\e03b",
	'earphones-alt' => "\e03c",
	'earphones' => "\e03d",
	'drop' => "\e03e",
	'drawer' => "\e03f",
	'docs' => "\e040",
	'directions' => "\e041",
	'direction' => "\e042",
	'diamond' => "\e043",
	'cup' => "\e044",
	'compass' => "\e045",
	'call-end' => "\e048",
	'calculator' => "\e049",
	'bubbles' => "\e04a",
	'briefcase' => "\e04b",
	'book-open' => "\e04c",
	'basket-loaded' => "\e04d",
	'basket' => "\e04e",
	'bag' => "\e04f",
	'action-undo' => "\e050",
	'action-redo' => "\e051",
	'trash' => "\e054",
	'tag' => "\e055",
	'support' => "\e056",
	'share-alt' => "\e05a",
	'share' => "\e05b",
	'question' => "\e05d",
	'pencil' => "\e05f",
	'note' => "\e060",
	'music-tone-alt' => "\e061",
	'music-tone' => "\e062",
	'microphone' => "\e063",
	'list' => "\e067",
	'home' => "\e069",
	'grid' => "\e06a",
	'graph' => "\e06b",
	'cursor' => "\e06e",
	'control-play' => "\e071",
	'calendar' => "\e075",
	'bulb' => "\e076",
	'bar-chart' => "\e077",
	'arrow-up' => "\e078",
	'arrow-right' => "\e079",
	'arrow-left' => "\e07a",
	'arrow-down' => "\e07b",
	'ban' => "\e07c",
	'bubble' => "\e07d",
	'camcorder' => "\e07e",
	'camera' => "\e07f",
	'check' => "\e080",
	'clock' => "\e081",
	'close' => "\e082",
	'envelope' => "\e086",
	'eye' => "\e087",
	'flag' => "\e088",
	'folder' => "\e089",
	'heart' => "\e08a",
	'info' => "\e08b",
	'key' => "\e08c",
	'link' => "\e08d",
	'lock' => "\e08e",
	'lock-open' => "\e08f",
	'magnifier' => "\e090",
	'magnifier-add' => "\e091",
	'magnifier-remove' => "\e092",
	'paper-clip' => "\e093",
	'paper-plane' => "\e094",
	'plus' => "\e095",
	'pointer' => "\e096",
	'power' => "\e097",
	'refresh' => "\e098",
	'reload' => "\e099",
	'settings' => "\e09a",
	'star' => "\e09b",
	'target' => "\e09e",
	'volume-1' => "\e09f",
	'volume-2' => "\e0a0",
	'volume-off' => "\e0a1",
	'users' => "\e001",
	'clock1' => "\e0a9",
	'search2' => "\e0a8",
	'head' => "\e0a7",
	'arrow-left1' => "\e0a2",
	'arrow-right1' => "\e0a3",
	'arrow-up1' => "\e0a4",
	'arrow-down1' => "\e0a5",
	'volume' => "\e0a6",
	'plus1' => "\e114",
	'minus' => "\e115",
	'check1' => "\e116",
	'cross' => "\e117",
	'menu2' => "\e120",
	'ellipsis' => "\e129",
	'search' => "\e618",
	'refresh1' => "\e61c",
	'close1' => "\e680",
	'angle-up' => "\e682",
	'angle-right' => "\e684",
	'angle-left' => "\e686",
	'angle-down' => "\e688",
	'refresh-2' => "\e6c2",
	'chevron-down' => "\e900",
	'chevron-left' => "\e901",
	'chevron-right' => "\e902",
	'chevron-small-down' => "\e903",
	'chevron-small-left' => "\e904",
	'chevron-small-right' => "\e905",
	'chevron-small-up' => "\e906",
	'chevron-thin-down' => "\e907",
	'chevron-thin-left' => "\e908",
	'chevron-thin-right' => "\e909",
	'chevron-thin-up' => "\e90a",
	'chevron-up' => "\e90b",
	'circular-graph' => "\e90c",
	'cross2' => "\e90d",
	'magnifying-glass' => "\e911",
	'menu3' => "\e912",
	'quote' => "\e915",
	'el-comment' => "\e800",
	'el-user' => "\e801",
	'el-tag' => "\e802",
	'el-down-dir' => "\e803",
	'el-edit' => "\e804",
	'el-category' => "\e805",
	'el-right-dir' => "\e806",
	'el-angle-left' => "\e807",
	'el-angle-right' => "\e808",
	'el-angle-up' => "\e809",
	'el-angle-down' => "\e80a",
	'el-minus' => "\e80b",
	'el-left-open' => "\e80c",
	'el-time' => "\e80d",
	'el-up' => "\e80e",
	'el-quote' => "\e80f",
	'el-bookmark' => "\e810",
	'el-left-dir' => "\e811",
	'el-up-open' => "\e812",
	'el-ok' => "\e813",
	'el-cancel' => "\e814",
	'el-comments' => "\e815",
	'el-search' => "\e816",
	'el-category2' => "\e817",
	'el-link' => "\e818",
	'el-up-dir' => "\e819",
	'el-info' => "\e81a",
	'el-share' => "\e81b",
	'el-folder-close' => "\e81c",
	'el-folder-open' => "\e81d",
	'el-right-open' => "\e81e",
	'el-home' => "\e81f",
	'el-menu' => "\e820",
	'el-plus' => "\e821",
	'el-down-open' => "\e822",
	'el-audio' => "\e823",
	'el-image' => "\e824",
	'el-camera' => "\e825",
	'el-down' => "\e826",
	'el-left' => "\e827",
	'el-right' => "\e828",
	'el-video' => "\e829",
	'el-aside' => "\e82a",
	'el-date' => "\e82b",
	'el-star-empty' => "\e82c",
	'el-star' => "\e82d",
	'el-mail' => "\e82e",
	'el-home-1' => "\e82f",
	'el-attach' => "\e830",
	'el-eye' => "\e831",
	'el-eye-off' => "\e832",
	'eye-on' => "\e831",
	'eye-off' => "\e832",
	'el-tags' => "\e833",
	'el-flag' => "\e834",
	'el-warning' => "\e835",
	'el-location' => "\e836",
	'el-trash' => "\e837",
	'el-doc' => "\e838",
	'el-phone' => "\e839",
	'el-cog' => "\e83a",
	'el-basket' => "\e83b",
	'el-basket-circled' => "\e83c",
	'el-wrench' => "\e83d",
	'el-wrench-circled' => "\e83e",
	'el-mic' => "\e83f",
	'el-volume' => "\e840",
	'el-volume-down' => "\e841",
	'el-volume-off' => "\e842",
	'el-headphones' => "\e843",
	'el-lightbulb' => "\e844",
	'el-resize-full' => "\e845",
	'el-resize-full-alt' => "\e846",
	'el-resize-small' => "\e847",
	'el-resize-vertical' => "\e848",
	'el-resize-horizontal' => "\e849",
	'el-move' => "\e84a",
	'el-zoom-in' => "\e84b",
	'el-zoom-out' => "\e84c",
	'el-arrows-cw' => "\e84d",
	'el-desktop' => "\e84e",
	'el-inbox' => "\e84f",
	'el-cloud' => "\e850",
	'el-book' => "\e851",
	'el-certificate' => "\e852",
	'el-tasks' => "\e853",
	'el-thumbs-up' => "\e854",
	'el-thumbs-down' => "\e855",
	'el-help-circled' => "\e856",
	'el-star-circled' => "\e857",
	'el-bell' => "\e858",
	'el-rss' => "\e859",
	'el-trash-circled' => "\e85a",
	'el-cogs' => "\e85b",
	'el-cog-circled' => "\e85c",
	'el-calendar-circled' => "\e85d",
	'el-mic-circled' => "\e85e",
	'el-volume-up' => "\e85f",
	'el-print' => "\e860",
	'el-edit-alt' => "\e861",
	'el-edit-2' => "\e862",
	'el-block' => "\e863",
);

$social_icons = array(
	'duckduckgo' => 'e801',
	'aim' => 'e802',
	'delicious' => 'e803',
	'paypal' => 'e804',
	'flattr' => 'e805',
	'android' => 'e806',
	'eventful' => 'e807',
	'smashingmagazine' => 'e808',
	'googleplus' => 'e809',
	'wikipedia' => 'e80a',
	'lanyrd' => 'e80b',
	'calendar' => 'e80c',
	'stumbleupon' => 'e80d',
	'500px' => 'e80e',
	'pinterest' => 'e80f',
	'bitcoin' => 'e810',
	'firefox' => 'e811',
	'foursquare' => 'e812',
	'chrome' => 'e813',
	'internetexplorer' => 'e814',
	'phone' => 'e815',
	'grooveshark' => 'e816',
	'99designs' => 'e817',
	'code' => 'e818',
	'digg' => 'e819',
	'spotify' => 'e81a',
	'reddit' => 'e81b',
	'about' => 'e81c',
	'codeopen' => 'e81d',
	'appstore' => 'e81e',
	'creativecommons' => 'e820',
	'dribbble' => 'e821',
	'evernote' => 'e822',
	'flickr' => 'e823',
	'link2' => 'e824',
	'viadeo' => 'e825',
	'instapaper' => 'e826',
	'weibo' => 'e827',
	'klout' => 'e828',
	'linkedin' => 'e829',
	'meetup' => 'e82a',
	'vk' => 'e82b',
	'plancast' => 'e82c',
	'disqus' => 'e82d',
	'feed' => 'e82e',
	'skype' => 'e82f',
	'twitter' => 'e830',
	'youtube' => 'e831',
	'vimeo' => 'e832',
	'windows' => 'e833',
	'xing' => 'e834',
	'yahoo' => 'e835',
	'email' => 'e837',
	'cloud' => 'e838',
	'myspace' => 'e839',
	'podcast' => 'e83a',
	'amazon' => 'e83b',
	'steam' => 'e83c',
	'link' => 'e83d',
	'dropbox' => 'e83e',
	'ebay' => 'e83f',
	'facebook' => 'e840',
	'github2' => 'e841',
	'github' => 'e842',
	'googleplay' => 'e843',
	'itunes' => 'e844',
	'plurk' => 'e845',
	'songkick' => 'e846',
	'lastfm' => 'e847',
	'gmail' => 'e848',
	'pinboard' => 'e849',
	'openid' => 'e84a',
	'quora' => 'e84b',
	'soundcloud' => 'e84c',
	'tumblr' => 'e84d',
	'wordpress' => 'e84f',
	'yelp' => 'e850',
	'intensedebate' => 'e851',
	'eventbrite' => 'e852',
	'scribd' => 'e853',
	'stripe' => 'e855',
	'opentable' => 'e856',
	'cart' => 'e857',
	'opera' => 'e858',
	'angellist' => 'e859',
	'instagram' => 'e85a',
	'dwolla' => 'e85b',
	'appnet' => 'e85c',
	'drupal' => 'e85f',
	'buffer' => 'e860',
	'pocket' => 'e861',
	'bitbucket' => 'e862',
	'phone2' => 'e863',
	'stackoverflow' => 'e865',
	'hackernews' => 'e866',
	'lkdto' => 'e867',
	'twitter2' => 'e868',
	'phone3' => 'e869',
	'mobile' => 'e86a',
	'support' => 'e86b',
	'twitch' => 'e86c',
	'beer' => 'e86d',
);
?>

<!doctype html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link rel="stylesheet" href="bootstrap.css" />
	<link rel="stylesheet" href="../admin/shortcodes.css" />
    <link rel="stylesheet" href="../../../resources/fonts/fontfaces.css" />
	<script type="text/javascript" src="jquery.js"></script>
	<script type="text/javascript" src="bootstrap.js"></script>
    <script type="text/javascript">
    $(document).ready(function() {
		prefix = '';
		if ( typeof top.cryout_shortcodes_prefix != 'undefined' ) prefix = top.cryout_shortcodes_prefix;

		current_text = top.tinymce.activeEditor.selection.getContent({format : 'text'});
		if (current_text.length<1) current_text = '';

        $('.glyphicons').on('click', 'li', function() {
            var iclass = $(this).find('.glyphicon').attr('class');
			var size = $(this).parents('body').find('#icon-size-input').val();

            top.tinymce.activeEditor.execCommand('mceInsertContent', false, '['+prefix+'icon name="' + iclass + '" size="'+ size + '"] '+current_text);
            top.tinymce.activeEditor.windowManager.close();
        });
    });
    </script>
    <style type="text/css">

    .glyphicons {
        display: block;
        overflow: hidden;
        padding-left: 0;
        list-style: none;
    }

    .glyphicons li {
        cursor: pointer;
        float: left;
        width: 12.5%;
        height: 100px;
        padding: 10px;
        margin: 0 -1px -1px 0;
        font-size: 12px;
        line-height: 1.4;
        text-align: center;
        border: 1px solid #DDD;
        word-break: break-all;
        -webkit-transition: .25s ease-out all;
        transition: .25s ease-out all;
    }

    .glyphicons li:last-child {
        margin: 0;
    }

    .glyphicons li:hover {
        background: rgba(0,0,0,.05);
    }

    .glyphicons .glyphicon {
        display: block;
        margin: 5px auto 10px;
        font-size: 24px;
    }

    h3:not(:first-child) {
        display: block;
        clear: both;
        float: none;
        margin-top: 2em;
    }

    </style>
</head>

<body>
    <div id="bs-wrapper">

		<form id="icons-form">
			<div class="form-group">
				<label for="icon-size-input">Size:</label>
				<select id="icon-size-input" class="form-control">
					<option value="xs">Smallest</option>
					<option value="sm">Small</option>
					<option value="md" selected="selected">Medium</option>
					<option value="lg">Large</option>
					<option value="xl">Larger</option>
					<option value="hb">Giant</option>
				</select>
			</div>
		</form>

        <h4> Block icons </h4>
        <ul class="glyphicons">
            <?php foreach ( $block_icons as $name => $char ) {
                echo '<li><i class="glyphicon blicon-' . $name . '"></i>' . $name . '</li>';
            } ?>
        </ul>

        <h3> Meta icons </h3>
        <ul class="glyphicons">
            <?php foreach ( $meta_icons as $name => $char ) {
                echo '<li><i class="glyphicon icon-' . $name . '"></i>' . $name . '</li>';
            } ?>
        </ul>

        <h3> Social icons </h3>
        <ul class="glyphicons">
            <?php foreach ( $social_icons as $name => $char ) {
                echo '<li><i class="glyphicon socicon-' . $name . '"></i>' . $name . '</li>';
            } ?>
        </ul>

    </div>
</body>

</html>
